<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\TheDesignator.Exception\TheDesignator.Exception.csproj" />
    <ProjectReference Include="..\TheDesignator.Application\TheDesignator.Application.csproj" />
    <ProjectReference Include="..\TheDesignator.Communication\TheDesignator.Communication.csproj" />
    <ProjectReference Include="..\TheDesignator.Infrastructure\TheDesignator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
